<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Product>XIVLauncher.Dalamud</Product>
        <AssemblyTitle>XIVLauncher.Dalamud</AssemblyTitle>
        <Description>Dalamud core components for XIVLauncher.</Description>
        <VersionPrefix>1.0.0</VersionPrefix>
        <Nullable>enable</Nullable>
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
        <DefineConstants>$(DefineConstants);WIN32</DefineConstants>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Deterministic>true</Deterministic>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <DefineConstants Condition=" '$(ExtraDefineConstants)' != '' ">$(DefineConstants);$(ExtraDefineConstants)</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Label="Configuration" Condition="'$(Configuration)'=='Release'">
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <PathMap>$(AppOutputBase)=C:\goatsoft\xl\XIVLauncher.Dalamud\</PathMap>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\XIVLauncher.Common\XIVLauncher.Common.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>XIVLauncher.Test</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommandLineParser"/>
        <PackageReference Include="Downloader"/>
        <PackageReference Include="Iced"/>
        <PackageReference Include="Newtonsoft.Json"/>
        <PackageReference Include="PInvoke.Kernel32"/>
        <PackageReference Include="Reloaded.Memory"/>
        <PackageReference Include="Reloaded.Memory.Buffers"/>
        <PackageReference Include="Reloaded.Memory.Sigscan"/>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Enrichers.Sensitive"/>
        <PackageReference Include="Serilog.Sinks.Async"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
        <PackageReference Include="Serilog.Sinks.Debug"/>
        <PackageReference Include="Serilog.Sinks.File"/>
        <PackageReference Include="SharedMemory"/>
        <PackageReference Include="SharpCompress"/>
        <PackageReference Include="System.Management"/>
        <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers"/>
    </ItemGroup>
</Project>
